runtime: go111
instance_class: F1
service: default
inbound_services:
- warmup
automatic_scaling:
  max_instances: 1
env_variables:
  GA_TRACKING_ID: UA-25397287-3

handlers:
- url: /static
  static_dir: static
- url: /robots.txt
  static_files: templates/robots.txt
  upload: templates/robots.txt
- url: /.*
  script: auto
